package bpserver

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"errors"
	"fmt"
	"math/big"
	"time"

	"github.com/local/reorigin-hotpursuit/legacytls"
)

const dirtySDK64RSAKeyBits = 1024

// GenerateDirtySDK64SelfSigned creates a conventional RSA/SHA-1 certificate
// whose public key fits Burnout Paradise's fixed-size DirtySDK 6.4 buffers.
// The game's parser accepts at most a 129-byte RSA modulus and a 256-byte
// SubjectPublicKeyInfo BIT STRING, so the 2048-bit certificate generated by the
// newer Hot Pursuit server is too large for this older client.
func GenerateDirtySDK64SelfSigned(hosts ...string) (*legacytls.Config, error) {
	key, err := rsa.GenerateKey(rand.Reader, dirtySDK64RSAKeyBits)
	if err != nil {
		return nil, err
	}
	now := time.Now()
	commonName := "localhost"
	if len(hosts) != 0 && hosts[0] != "" {
		commonName = hosts[0]
	}
	tmpl := &x509.Certificate{
		SerialNumber:       new(big.Int).SetInt64(now.UnixNano()),
		Subject:            pkix.Name{CommonName: commonName, Organization: []string{"ReOrigin Local Emulator"}},
		NotBefore:          now.Add(-time.Hour),
		NotAfter:           now.AddDate(10, 0, 0),
		SignatureAlgorithm: x509.SHA1WithRSA,
		KeyUsage:           x509.KeyUsageKeyEncipherment | x509.KeyUsageDigitalSignature,
		ExtKeyUsage:        []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:           hosts,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, err
	}
	return &legacytls.Config{Certificate: [][]byte{der}, PrivateKey: key}, nil
}

// ValidateDirtySDK64Certificate rejects certificate keys that the retail
// client's fixed-size X.509/RSA parser cannot represent.
func ValidateDirtySDK64Certificate(config *legacytls.Config) error {
	if config == nil || config.PrivateKey == nil || len(config.Certificate) == 0 {
		return errors.New("certificate and RSA private key required")
	}
	leaf, err := x509.ParseCertificate(config.Certificate[0])
	if err != nil {
		return fmt.Errorf("parse leaf certificate: %w", err)
	}
	publicKey, ok := leaf.PublicKey.(*rsa.PublicKey)
	if !ok {
		return errors.New("leaf certificate public key is not RSA")
	}
	if publicKey.N.BitLen() > dirtySDK64RSAKeyBits {
		return fmt.Errorf("leaf certificate RSA key is %d bits; Burnout Paradise DirtySDK 6.4 supports at most %d bits", publicKey.N.BitLen(), dirtySDK64RSAKeyBits)
	}
	if config.PrivateKey.N.Cmp(publicKey.N) != 0 || config.PrivateKey.E != publicKey.E {
		return errors.New("leaf certificate does not match the configured RSA private key")
	}
	return nil
}
